export const countryCodes = [
  { name: "Afghanistan", iso: "AF", code: "+93" },
  { name: "Aland Islands", iso: "AX", code: "+358" },
  { name: "Albania", iso: "AL", code: "+355" },
  { name: "Algeria", iso: "DZ", code: "+213" },
  { name: "American Samoa", iso: "AS", code: "+1" },
  { name: "Andorra", iso: "AD", code: "+376" },
  { name: "Angola", iso: "AO", code: "+244" },
  { name: "Anguilla", iso: "AI", code: "+1" },
  { name: "Antarctica", iso: "AQ", code: "+672" },
  { name: "Antigua and Barbuda", iso: "AG", code: "+1" },
  { name: "Argentina", iso: "AR", code: "+54" },
  { name: "Armenia", iso: "AM", code: "+374" },
  { name: "Aruba", iso: "AW", code: "+297" },
  { name: "Australia", iso: "AU", code: "+61" },
  { name: "Austria", iso: "AT", code: "+43" },
  { name: "Azerbaijan", iso: "AZ", code: "+994" },
  { name: "Bahamas", iso: "BS", code: "+1" },
  { name: "Bahrain", iso: "BH", code: "+973" },
  { name: "Bangladesh", iso: "BD", code: "+880" },
  { name: "Barbados", iso: "BB", code: "+1" },
  { name: "Belarus", iso: "BY", code: "+375" },
  { name: "Belgium", iso: "BE", code: "+32" },
  { name: "Belize", iso: "BZ", code: "+501" },
  { name: "Benin", iso: "BJ", code: "+229" },
  { name: "Bermuda", iso: "BM", code: "+1" },
  { name: "Bhutan", iso: "BT", code: "+975" },
  { name: "Bolivia", iso: "BO", code: "+591" },
  { name: "Bosnia and Herzegovina", iso: "BA", code: "+387" },
  { name: "Botswana", iso: "BW", code: "+267" },
  { name: "Brazil", iso: "BR", code: "+55" },
  { name: "Brunei Darussalam", iso: "BN", code: "+673" },
  { name: "Bulgaria", iso: "BG", code: "+359" },
  { name: "Burkina Faso", iso: "BF", code: "+226" },
  { name: "Burundi", iso: "BI", code: "+257" },
  { name: "Cambodia", iso: "KH", code: "+855" },
  { name: "Cameroon", iso: "CM", code: "+237" },
  { name: "Canada", iso: "CA", code: "+1" },
  { name: "Chile", iso: "CL", code: "+56" },
  { name: "China", iso: "CN", code: "+86" },
  { name: "Colombia", iso: "CO", code: "+57" },
  { name: "Costa Rica", iso: "CR", code: "+506" },
  { name: "Croatia", iso: "HR", code: "+385" },
  { name: "Cuba", iso: "CU", code: "+53" },
  { name: "Cyprus", iso: "CY", code: "+357" },
  { name: "Czech Republic", iso: "CZ", code: "+420" },
  { name: "Denmark", iso: "DK", code: "+45" },
  { name: "Dominican Republic", iso: "DO", code: "+1" },
  { name: "Ecuador", iso: "EC", code: "+593" },
  { name: "Egypt", iso: "EG", code: "+20" },
  { name: "El Salvador", iso: "SV", code: "+503" },
  { name: "Estonia", iso: "EE", code: "+372" },
  { name: "Ethiopia", iso: "ET", code: "+251" },
  { name: "Fiji", iso: "FJ", code: "+679" },
  { name: "Finland", iso: "FI", code: "+358" },
  { name: "France", iso: "FR", code: "+33" },
  { name: "Germany", iso: "DE", code: "+49" },
  { name: "Ghana", iso: "GH", code: "+233" },
  { name: "Greece", iso: "GR", code: "+30" },
  { name: "Greenland", iso: "GL", code: "+299" },
  { name: "Guatemala", iso: "GT", code: "+502" },
  { name: "Hong Kong", iso: "HK", code: "+852" },
  { name: "Hungary", iso: "HU", code: "+36" },
  { name: "Iceland", iso: "IS", code: "+354" },
  { name: "India", iso: "IN", code: "+91" },
  { name: "Indonesia", iso: "ID", code: "+62" },
  { name: "Iran", iso: "IR", code: "+98" },
  { name: "Iraq", iso: "IQ", code: "+964" },
  { name: "Ireland", iso: "IE", code: "+353" },
  { name: "Israel", iso: "IL", code: "+972" },
  { name: "Italy", iso: "IT", code: "+39" },
  { name: "Jamaica", iso: "JM", code: "+1" },
  { name: "Japan", iso: "JP", code: "+81" },
  { name: "Jordan", iso: "JO", code: "+962" },
  { name: "Kenya", iso: "KE", code: "+254" },
  { name: "Kuwait", iso: "KW", code: "+965" },
  { name: "Laos", iso: "LA", code: "+856" },
  { name: "Latvia", iso: "LV", code: "+371" },
  { name: "Lebanon", iso: "LB", code: "+961" },
  { name: "Lithuania", iso: "LT", code: "+370" },
  { name: "Luxembourg", iso: "LU", code: "+352" },
  { name: "Malaysia", iso: "MY", code: "+60" },
  { name: "Maldives", iso: "MV", code: "+960" },
  { name: "Malta", iso: "MT", code: "+356" },
  { name: "Mauritius", iso: "MU", code: "+230" },
  { name: "Mexico", iso: "MX", code: "+52" },
  { name: "Monaco", iso: "MC", code: "+377" },
  { name: "Mongolia", iso: "MN", code: "+976" },
  { name: "Morocco", iso: "MA", code: "+212" },
  { name: "Nepal", iso: "NP", code: "+977" },
  { name: "Netherlands", iso: "NL", code: "+31" },
  { name: "New Zealand", iso: "NZ", code: "+64" },
  { name: "Nigeria", iso: "NG", code: "+234" },
  { name: "North Korea", iso: "KP", code: "+850" },
  { name: "Norway", iso: "NO", code: "+47" },
  { name: "Oman", iso: "OM", code: "+968" },
  { name: "Pakistan", iso: "PK", code: "+92" },
  { name: "Palestine", iso: "PS", code: "+970" },
  { name: "Panama", iso: "PA", code: "+507" },
  { name: "Paraguay", iso: "PY", code: "+595" },
  { name: "Peru", iso: "PE", code: "+51" },
  { name: "Philippines", iso: "PH", code: "+63" },
  { name: "Poland", iso: "PL", code: "+48" },
  { name: "Portugal", iso: "PT", code: "+351" },
  { name: "Qatar", iso: "QA", code: "+974" },
  { name: "Romania", iso: "RO", code: "+40" },
  { name: "Russia", iso: "RU", code: "+7" },
  { name: "Saudi Arabia", iso: "SA", code: "+966" },
  { name: "Singapore", iso: "SG", code: "+65" },
  { name: "South Africa", iso: "ZA", code: "+27" },
  { name: "South Korea", iso: "KR", code: "+82" },
  { name: "Spain", iso: "ES", code: "+34" },
  { name: "Sri Lanka", iso: "LK", code: "+94" },
  { name: "Sweden", iso: "SE", code: "+46" },
  { name: "Switzerland", iso: "CH", code: "+41" },
  { name: "Taiwan", iso: "TW", code: "+886" },
  { name: "Thailand", iso: "TH", code: "+66" },
  { name: "Turkey", iso: "TR", code: "+90" },
  { name: "Uganda", iso: "UG", code: "+256" },
  { name: "Ukraine", iso: "UA", code: "+380" },
  { name: "United Arab Emirates", iso: "AE", code: "+971" },
  { name: "United Kingdom", iso: "GB", code: "+44" },
  { name: "United States", iso: "US", code: "+1" },
  { name: "Uruguay", iso: "UY", code: "+598" },
  { name: "Vietnam", iso: "VN", code: "+84" },
  { name: "Zambia", iso: "ZM", code: "+260" },
  { name: "Zimbabwe", iso: "ZW", code: "+263" },
];
